language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm test
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0
deploy:
  provider: heroku
  app: wbs-travis-intro
  api_key:
    secure: kGGGoLUXLsEgk+BlNfvH9JMQ1XAR5W5+KoaRwEz3oHkr5ig1HeY+tZLxS4HnHz6CpHLn4Qtmlb3qbt60cW7nNpy7XCbp48wTxouJkAY5XEum0yB1OLpBv4Stcwe5ywrgiOCq2EF33yxi6AnAyETzDZJr92zJMwSIANPA9u1C1B8xJpywXZ5sjE4eM9KjGPATLuUn4S67PiXAONDD20LlbPtN4rFOgWkei7mI1r5G+vbcCboxdskZ/cW2/398BxEJ6HLhGMXeZxbiY+6Q0pd66hR81RAJRnUolN+z5jjifEYqp06LafszQrXgHGGn2BTYF6E66yV0LNm8QfLzEL5Qp7d/+JABn+2u+TPJwMcDf2Kv3+v70/wzCtDqJ18vQ4cKw7BBe8giTEQlHMScYvCo9+0mKwVtEeDh9OifJas5DN4gPd9vVgUfuofAX+d1rDPwtpBqf0ZBf6g/r1MSDK+pMyYRB9n1/9R1TZp44sGMMNh+Iyw1I12TSe9p8nO4VAMkN2yGS0nxC20IfgRdyeCXgnjpIt2B/nF5tLbdabFwCr/v9ySqkVKK94XoJ8qfMT7lRw3dxJBAk9s1qm/wMoQ61ENAZHtCxWJOlaOl+CfoMb18jl3eCv/M41qyDZHDjQYZN0vXg6+ffPMXSIXDEVaxZjoi8w/hZ6e0W1Bc+lOW3k0=
  on: main
